# Generated by Django 4.2 on 2026-01-23 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('address_id', models.CharField(blank=True, max_length=50)),
                ('village', models.CharField(blank=True, max_length=100)),
                ('street', models.CharField(blank=True, max_length=200)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('house_number_affix', models.CharField(blank=True, max_length=10)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('owner_name', models.CharField(blank=True, max_length=100)),
                ('owner_surname', models.CharField(blank=True, max_length=100)),
                ('owner_phone_1', models.CharField(blank=True, max_length=20)),
                ('owner_phone_2', models.CharField(blank=True, max_length=20)),
                ('pop_code', models.CharField(blank=True, max_length=20)),
                ('gebaute_units', models.IntegerField(blank=True, null=True)),
                ('hbg_termin', models.DateTimeField(blank=True, null=True)),
                ('ausbau_termin', models.DateTimeField(blank=True, null=True)),
                ('kl_15m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('kl_20m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('kl_30m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('kl_50m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('kl_80m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('kl_100m', models.IntegerField(blank=True, choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], default=0, null=True)),
                ('keller', models.CharField(blank=True, choices=[('', '---------'), ('Ja', 'Ja'), ('Nein', 'Nein')], max_length=10)),
                ('huep', models.CharField(blank=True, choices=[('', '---------'), ('Ja', 'Ja'), ('Nein', 'Nein')], max_length=10)),
                ('spleissen', models.CharField(blank=True, choices=[('', '---------'), ('Ja', 'Ja'), ('Nein', 'Nein')], max_length=10)),
                ('comments', models.TextField(blank=True, verbose_name='Comments/Notes')),
                ('hbg', models.CharField(blank=True, choices=[('', '---------'), ('Ja', 'Ja'), ('Nein', 'Nein')], max_length=10)),
                ('infra_type', models.CharField(blank=True, choices=[('', '---------'), ('ohne', 'Ohne Infra'), ('mit', 'Mit Infra')], max_length=10)),
                ('status', models.CharField(blank=True, choices=[('', '---------'), ('klarungen', 'Klarungen'), ('auskundung', 'Auskundung terminiert'), ('ausbau_terminiert', 'Ausbau terminiert'), ('ausbau_abgeschlossen', 'Ausbau Abgeschlossen'), ('bezahlt', 'Bezahlt')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='properties', to='properties.team'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='properties.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['team__name'],
                'unique_together': {('user', 'team')},
            },
        ),
    ]
