# Generated by Django 4.2 on 2026-01-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='infra_type',
        ),
        migrations.AddField(
            model_name='property',
            name='mit_infra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Mit Infra'),
        ),
        migrations.AddField(
            model_name='property',
            name='ohne_infra',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Ohne Infra'),
        ),
    ]
