# Generated by Django 4.2 on 2026-02-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_infra_type_property_mit_infra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('klarungen', 'Klarungen'), ('auskundung', 'Auskundung terminiert'), ('zustimmung_eigentuemer', 'Zustimmung des Eigentümers'), ('bereit_zur_umsetzung', 'Bereit zur Umsetzung'), ('ausbau_terminiert', 'Ausbau terminiert'), ('ausbau_abgeschlossen', 'Ausbau Abgeschlossen'), ('bezahlt', 'Bezahlt'), ('storniert', 'Storniert')], max_length=50),
        ),
    ]
